export const properties = {
  url: "http://localhost:8080/ProjetJEE-1.0-SNAPSHOT/api/",
  registerUser: "users/auth/register-user",
  checkUser: "users/auth/check-user",
  company: "company/all",
  students: "school/students/",
  educations: "student/save/education",
  skills: "student/save/skill",
  experiences: "student/save/experience",
  languages: "student/save/language",
  StudentEducation: "student/educations/",
  StudentSkill: "student/skills/",
  StudentLanguage: "student/languages/",
  StudentExperience: "student/experiences/",
};
